# Generated by Django 3.1.2 on 2020-10-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_buyer_buyertobids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='ownership',
            field=models.CharField(choices=[('owner', 'watchlist'), ('Won', 'Lost')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyertobids',
            name='bid',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyertobids',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.buyer'),
            preserve_default=False,
        ),
    ]
